version: '3.8'

services:
  word-excel-replace:
    image: ghcr.io/${GITHUB_USERNAME:-MaroD1M}/WordReplace:${TAG:-latest}
    container_name: WordReplace
    network_mode: bridge
    ports:
      - "${EXTERNAL_PORT:-12344}:8501"
    restart: no
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false







