version: '3.8'

services:
  word-excel-replace:
    image: ghcr.io/MaroD1M/WordReplace:latest
    container_name: WordReplace
    network_mode: bridge
    ports:
      - "12344:8501"
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false







